#3087: .travis.yml, use multiline 'after_success'

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -13,8 +13,6 @@ env:
   - PARALLEL=frontend
   - PARALLEL=backend
   - COVERALLS_PARALLEL=true
-  - LINT_EXIT=0
-  - TEST_EXIT=0
 
 ##
 ## implement coveralls.io webhook
@@ -51,6 +49,17 @@ script:
 after_success:
   - coverage combine
   - coveralls
-  - if [ "$LINT_EXIT" -gt 0 ] && [ "$TEST_EXIT" -gt 0 ]; then echo "Lint ($LINT_EXIT) and Unit Tests failed" && exit 1; fi
-  - if [ "$LINT_EXIT" -gt 0 ]; then echo "Lint Failed ($LINT_EXIT)" && exit 1; fi
-  - if [ "$TEST_EXIT" -gt 0 ]; then echo 'Unit Tests Failed' && exit 1; fi
+  - if [ -z ${var+LINT_EXIT} ] &&
+       [ -z ${var+TEST_EXIT} ] &&
+       [ "$LINT_EXIT" -gt 0 ] &&
+       [ "$TEST_EXIT" -gt 0 ]; then
+           echo "Lint ($LINT_EXIT) and Unit Tests failed" && exit 1;
+    fi
+  - if [ -z ${var+LINT_EXIT} ] &&
+       [ "$LINT_EXIT" -gt 0 ]; then
+           echo "Lint Failed ($LINT_EXIT)" && exit 1;
+    fi
+  - if [ -z ${var+TEST_EXIT} ] &&
+       [ "$TEST_EXIT" -gt 0 ]; then
+           echo 'Unit Tests Failed' && exit 1;
+    fi
