#2935: install_rancher, ensure 'wget' on linux

diff --git a/install_rancher b/install_rancher
--- a/install_rancher
+++ b/install_rancher
@@ -32,7 +32,9 @@ if [ "$DISTRO_TYPE" = 'unix' ]; then
     sudo chmod +x /usr/local/bin/rancher-compose
 
 elif [ "$DISTRO_TYPE" = 'linux' ]; then
-    DISTRO=$(cat /etc/*-release)
+    if [ ! $(which wget) ]; then
+        sudo apt-get -y install wget || sudo yum y install wget || echo 'wget cannot install' && exit 1
+    fi
 
     wget "$RANCHER_REPO"/releases/download/v${RANCHER_VERSION}/"$RANCHER_DISTRO"-v${RANCHER_VERSION}-rc1.tar.gz
     tar zxf "$RANCHER_DISTRO"-v${VERSION_NUM}-rc1.tar.gz
