#2935: install_rancher, fix trailing condition

diff --git a/install_rancher b/install_rancher
--- a/install_rancher
+++ b/install_rancher
@@ -32,7 +32,7 @@ if [ "$DISTRO_TYPE" = 'unix' ]; then
 
 elif [ "$DISTRO_TYPE" = 'linux' ]; then
     if [ ! $(which wget) ]; then
-        sudo apt-get -y install curl || sudo yum -y install curl || echo 'curl cannot install' && exit 1
+        sudo apt-get -y install curl || sudo yum -y install curl || (echo 'curl cannot install' && exit 1)
     fi
 
     curl -OL "$RANCHER_REPO/releases/download/$RANCHER_VERSION/$RANCHER_DISTRO-$RANCHER_VERSION.tar.gz"
